# DataFrame
When we combine multiple Series then it  will became DataFrame.

In [3]:
import numpy as np
import pandas as pd

1. Creating a DataFrame

In [17]:
# using dictionary
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [18]:
df = pd.DataFrame(data)

In [19]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [25]:
# using list
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df2 = pd.DataFrame(data_list)

In [26]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [27]:
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

2. Selection and indexing of columns

In [28]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
df2['Name']   # single column select

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [30]:
df2[['Name', 'City']]  # multiple column select (list of list)

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

3. Creatng a new column

In [31]:
df2['Designation'] = ['Doctor', 'Eng.', 'Doctor', 'Eng']

In [32]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000         Eng

4. Removing columns and rows

In [37]:
# it show only copy data not deleted from original data. for deleted in original data we use (inplace = True)
# by default axis = 0 --> for horizonral(row), &&&  axis = 1 ---> for vertical(column)
df2.drop('Designation', axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [36]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000         Eng

In [38]:
# deleted data from original data.  using (inplace = True)
df2.drop('Designation', axis = 1, inplace=True)

In [39]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [41]:
# removing multiple columns.  (removing from original data use inplace = True)
df2.drop(['City', 'Age'], axis = 1)

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [42]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [43]:
# Removing rows ---> use axis = 0  (by default axis = 0)
df2.drop(0, )

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [45]:
df2.drop(0, axis = 0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [46]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [47]:
# removing multiple rows
df2.drop([1,2,3], axis = 0)

   Name  Age      City  Salary
0  John   28  New York   65000

In [48]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

5. Selecting rows

In [56]:
# it gives location of value.
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [57]:
df2.loc[[0]]

   Name  Age      City  Salary
0  John   28  New York   65000

In [58]:
df2.loc[[1,2]]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [59]:
# iloc[]  -->> it gives value of index location
df2.iloc[2]

Name       Peter
Age           29
City      Berlin
Salary     62000
Name: 2, dtype: object

In [60]:
df2.iloc[[3]]

    Name  Age    City  Salary
3  Linda   42  London   85000

In [61]:
df.iloc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

6. Selecting subset of rows and columns

In [62]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [67]:
df.loc[[0,1]][['Name','City']]

   Name      City
0  John  New York
1  Anna     Paris

In [68]:
df.loc[[2,3]] [['Name', 'Age']]

    Name  Age
2  Peter   29
3  Linda   42

7. Conditional conditions

In [70]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [74]:
# I only want to see those people whose age is above 30
df2[df['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [77]:
# I only want people whose age is above 30 and their city must be paris.
df2[(df2['Age'] > 30) & (df2['City'] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000