# Any changes are not apply in orginal data whenever we are not usinig (inplace = True).
# use (inplace = True) where you want to changes apply in original data.

In [1]:
import numpy as np
import pandas as pd

Findng Missing Values

In [13]:
# nan --> null values --> not a number
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)

In [14]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [15]:
# find how many values are missing (nan or null) -->  df.isna() -->> gives true where value are missing otherwise false.
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [16]:
# sum of all missing values in each columns.
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [17]:
# check that all columns have exist a null value. if exist --> Ture  , otherwise --> false
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

Removing missing Data

In [21]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [22]:
# remove all rows in which null values exist.
# dropna() --> select rows wise.
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [23]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [26]:
# threshold --> if thresh = 3 --> it means if in each row minimum 3 non-null value exist . except these rows all rows are removed in which rows, non-null values < 3.
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

Filling the missing data

In [27]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [31]:
# all null values replaced(filled) by 0.
# fillna() --> selsect column wise.
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [35]:
# each columns null value replaced by user defined values (different for each or same).
values = {'A':50, 'B': 100, 'C':300, 'D':400}
df.fillna(value=values)

      A  B      C      D
0   1.0  1    1.0    1.0
1   2.0  2    2.0  400.0
2  50.0  3    3.0  400.0
3   4.0  4  300.0  400.0
4   5.0  5  300.0    5.0

In [38]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [39]:
df.mean()

A    3.0
B    3.0
C    2.0
D    3.0
dtype: float64

In [40]:
# fill missing values of each column by mean of each columns .
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0